### ISSUE TITLE
请问如何在移动端打开

### ISSUE THREAD

**Issue by colorbeach** [wudeh/flutter_music_code#1]
flutter新手，看到chrome运行的效果很赞，但是貌似只能chrome运行，ios和安卓要如何运行呢

**Comment by wudeh** [comment]
> flutter新手，看到chrome运行的效果很赞，但是貌似只能chrome运行，ios和安卓要如何运行呢

😂😂😂你这先后顺序有点不对吧，用flutter一般都是先开发安卓ios的，你怎么跑web去了，我这个项目web端和文件相关的功能不支持的

**Comment by wudeh** [comment]
> flutter新手，看到chrome运行的效果很赞，但是貌似只能chrome运行，ios和安卓要如何运行呢

你可以flutter doctor看一下哪些有问题，网上搜一下教程吧，android studio有模拟器可以运行，或者下载安卓模拟器，真机连接调试也可以，😂😂flutter安装有点麻烦，我也说不清楚，好久之前安装的了

**Comment by colorbeach** [comment]
> > flutter新手，看到chrome运行的效果很赞，但是貌似只能chrome运行，ios和安卓要如何运行呢
> 
> 😂😂😂你这先后顺序有点不对吧，用flutter一般都是先开发安卓ios的，你怎么跑web去了，我这个项目web端和文件相关的功能不支持的

纳尼😂

您误解了，并非是我想用chrome打开，而是clone之后，ios和android模拟器都无法打开，连接模拟器一会儿后自动直接退出，只有chrome的方式能运行。

`Launching lib[/main.dart]() on iPhone 12 Pro in debug mode...
lib/main.dart:1
Xcode build done.                                           13.6s
Connecting to VM Service at ws://127.0.0.1:52962[/wfKfKvKCnNE]()=[/ws]()
Lost connection to device.
Exited (sigterm)`

不过估计也不是您预期的结果，可能是flutter版本问题吧😂

感谢回复。

**Comment by wudeh** [comment]
> > > flutter新手，看到chrome运行的效果很赞，但是貌似只能chrome运行，ios和安卓要如何运行呢
> > 
> > 
> > 😂😂😂你这先后顺序有点不对吧，用flutter一般都是先开发安卓ios的，你怎么跑web去了，我这个项目web端和文件相关的功能不支持的
> 
> 纳尼😂
> 
> 您误解了，并非是我想用chrome打开，而是clone之后，ios和android模拟器都无法打开，连接模拟器一会儿后自动直接退出，只有chrome的方式能运行。
> 
> `Launching lib[/main.dart]() on iPhone 12 Pro in debug mode... lib/main.dart:1 Xcode build done. 13.6s Connecting to VM Service at ws://127.0.0.1:52962[/wfKfKvKCnNE]()=[/ws]() Lost connection to device. Exited (sigterm)`
> 
> 不过估计也不是您预期的结果，可能是flutter版本问题吧😂
> 
> 感谢回复。

😂😂我版本是2.10

**Comment by colorbeach** [comment]
> 

巧...巧了😂，您是否记得是模拟器上要设置吗？我这只有chrome可以打开，是ws这个协议的问题吗
`└> flutter --version
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (7 weeks ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2`

**Comment by wudeh** [comment]
> > 
> 
> 巧...巧了😂，您是否记得是模拟器上要设置吗？我这只有chrome可以打开，是ws这个协议的问题吗 `└> flutter --version Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git Framework • revision 097d3313d8 (7 weeks ago) • 2022-02-18 19:33:08 -0600 Engine • revision a83ed0e5e3 Tools • Dart 2.16.1 • DevTools 2.9.2`

😂没做过什么设置啊，你可以试试自己新建个项目迁移下代码试试；或者等我这边有时间升级下flutter版本看看😂

**Comment by colorbeach** [comment]
> > > 
> > 
> > 
> > 巧...巧了😂，您是否记得是模拟器上要设置吗？我这只有chrome可以打开，是ws这个协议的问题吗 `└> flutter --version Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git Framework • revision 097d3313d8 (7 weeks ago) • 2022-02-18 19:33:08 -0600 Engine • revision a83ed0e5e3 Tools • Dart 2.16.1 • DevTools 2.9.2`
> 
> 😂没做过什么设置啊，你可以试试自己新建个项目迁移下代码试试；或者等我这边有时间升级下flutter版本看看😂

好的，感谢😘

**Comment by colorbeach** [comment]
调试了一下，是这个引起的，注释掉就能正常启动了，请问去掉这个会有什么影响吗

> void initDownload() async {
          WidgetsFlutterBinding.ensureInitialized();
          await FlutterDownloader.initialize(
        debug: true // optional: set false to disable printing logs to console
        );
    FlutterDownloader.registerCallback(downloadCallback);
  }

**Comment by wudeh** [comment]
> 调试了一下，是这个引起的，注释掉就能正常启动了，请问去掉这个会有什么影响吗
> 
> > void initDownload() async {
> > WidgetsFlutterBinding.ensureInitialized();
> > await FlutterDownloader.initialize(
> > debug: true // optional: set false to disable printing logs to console
> > );
> > FlutterDownloader.registerCallback(downloadCallback);
> > }

😂你真有毅力，这是下载音乐用的，插件要求要调用的，你可以去pub.flutter-io.cn上搜一下flutter_downloader这个插件

**Comment by colorbeach** [comment]
> > 调试了一下，是这个引起的，注释掉就能正常启动了，请问去掉这个会有什么影响吗
> > > void initDownload() async {
> > > WidgetsFlutterBinding.ensureInitialized();
> > > await FlutterDownloader.initialize(
> > > debug: true // optional: set false to disable printing logs to console
> > > );
> > > FlutterDownloader.registerCallback(downloadCallback);
> > > }
> 
> 😂你真有毅力，这是下载音乐用的，插件要求要调用的，你可以去pub.flutter-io.cn上搜一下flutter_downloader这个插件

感谢
